---
- name: Example of provisioning servers
  connection: local
  hosts: localhost
  tasks:
    - name: Create security group
      local_action:
        module: ec2_group
        name: jenkins_group
        description: Access to the Episode2 servers
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Launch instances
      local_action:
        module: ec2
        region: us-east-1
        keypair: id_rsa
        group: jenkins_group
        instance_type: t1.micro
        image: ami-a73264ce
        count: 2
        wait: yes
      register: ec2

    - name: Add jenkins instances to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=ep2
      with_items: ec2.instances

    - name: Add tag to instances
      local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
      with_items: ec2.instances
      args:
        tags:
          Name: Jenkins

    - name: Wait for SSH to be available
      pause: minutes=1


- name: Configure provisioned servers
  hosts: ep2
  user: ubuntu
  sudo: True
  tasks:
    - include: roles/common/install-awscli.yml